config/routes.rb
Rails.application.routes.draw do
  resources :elements
  resources :comments
  devise_for :authors
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"

  get '/view/:id', to: 'posts#show', as: 'view'

  resources :authors
  resources :posts do
    resources :elements
    resources :comments
  end





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, optional: true

  has_rich_text :comment
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: {in: ['paragraph', 'image', 'video-embed'] }

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author

  has_many :elements, dependent: :destroy

  has_one_attached :header_image

  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_author!
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.author = current_author
    @comment.save!

    if @comment.save
      redirect_to view_path(@post)
   else
      flash[:alert] = "Comment was not created"
      redirect_to view_path(@post)
   end

  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to view_path(@post)
  end


  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_post
  before_action :set_element, only: %i[ edit update destroy ]


  def set_post
    @post = current_author.posts.find(params[:post_id])
  end

  # POST /elements or /elements.json
  def create
    @element = @post.elements.build(element_params)

    if @element.save
      notice = nil
    else
      notice = redirect_to edit_post_path(@post), notice: @post.errors.full_messages.join(",")
    end
    
    redirect_to edit_post_path(@post), notice: notice
  end

  def edit
    @paragraph = @post.elements.build(element_type: 'paragraph')
  end

  # PATCH/PUT /elements/1 or /elements/1.json
  def update
    @element.update(element_params)
    redirect_to edit_post_path(@element.post)
  end

  # DELETE /elements/1 or /elements/1.json
  def destroy
    @element.destroy
    redirect_to edit_post_path(@element.post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_params
      params.require(:element).permit(:element_type, :content, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @authors = Author.all
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ edit update destroy ]

    # GET /posts or /posts.json
    def index
      @posts = current_author.posts
    end

    def show
      @post = Post.find(params[:id])
      @comments = @post.comments.order(created_at: :desc)
    end

    # GET /posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /posts/1/edit
    def edit
      @paragraph = @post.elements.build(element_type: 'paragraph')
      @image = @post.elements.build(element_type: 'image')
    end

    # POST /posts or /posts.json
    def create
      @post = current_author.posts.build(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to edit_post_path(@post) }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to edit_post_path(@post) }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1 or /posts/1.json
    def destroy
      @post.destroy

      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end



    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :description, :header_image)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class = "container mt-4 text-cyprus ripple border border-crush border-1" style = "padding: 1em;">
    <span> Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.author.present? ? comment.author.email : 'anon' %> </span>
    <% if current_author == comment.try(:author) %>
        <div class = "button-group float-end">
            <%= button_to "Delete", [post, comment], class:"btn btn-primary btn-sm align-center", method: :delete %>
        </div>
    <% end %>
    <hr />
    <%= comment.comment %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @post.comments.build]) do |form| %>
    <div class="ripple text-cyprus border border-crush border-1 p-2">
        <%= form.rich_text_area :comment, class: 'mt-2 mb-2' %>
        <%= form.submit "Leave a reply", class: "btn btn-primary mt-2 mb-2" %>
    </div>
<% end %>

app/views/home/index.html.erb
<h1 class="m-3 mb-4">Feed</h1>


    <% @posts.each do |post|%>
        <div class='card mb-3 m-3 ripple post'>
            <div class='card-body ripple post'>
                <div class= "row">
                    <div class= 'col-md-2'>
                        <% if post.header_image.present? %>
                            <%= link_to view_path(post), class: 'text-decoration-none' do %>
                            <div class= 'header-img' style="background-image: url(<%= url_for(post.header_image) %>);"></div>
                            <% end %>
                        <% end %>
                    </div>

                    <div class= 'col-md-8'>
                        <%= link_to view_path(post), class: 'text-decoration-none' do %>
                            <h5 class='card-title text-cyprus'><%= post.title %></h5>
                            <p class= 'text-seafloor'><%= post.description %></p>
                            <p class="align-bottom text-secondary"><span> Posted <%= time_ago_in_words(post.created_at) %> ago by <%= post.author.present? ? post.author.email : 'anon' %> </span>  </p>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light crush fixed-top">
  <div class="container">
      <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item active">
          <%= link_to "Home", home_index_path, class: "nav-link remove-submit-btn-style text-ripple" %>
        </li>
        <% if author_signed_in? %>
            <li class="nav-item">
                <%= link_to "My Posts", posts_path, class: "nav-link remove-submit-btn-style text-ripple" %>
            </li>
            <li class="nav-item">
                <%= button_to "Sign out", destroy_author_session_path, :method => :delete, class:"nav-link remove-submit-btn-style text-ripple", data:{turbo:false} %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= button_to "Sign up", new_author_registration_path, class:"nav-link remove-submit-btn-style text-ripple" %>
            </li>
            <li class="nav-item">
                <%= button_to "Sign in", author_session_path, class:"nav-link remove-submit-btn-style text-ripple" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>




app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class= 'cyprus text-ripple'>
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= render "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="text-cyprus">
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class = "form-group">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: 'form-control mb-2' %>
    </div>

    <div class = "form-group">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, class: 'form-control mb-3' %>
    </div>

    <div class = "form-group">
      <%= form.label :header_image, style: "display: block" %>
      <%= form.file_field :header_image, class: 'form-control mb-3' %>
      <div class="mt-1 mb-1">
        <% if post.header_image.present? %>
          <%= image_tag(post.header_image, width: '100%')%>
        <% end %>
      </div>
    </div>

    <div class = "actions">
      <%= form.submit class: "btn btn-primary w-100" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Published:</strong>
    <%= post.published %>
  </p>

  <p>
    <strong>Published at:</strong>
    <%= post.published_at %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= post.author.email %>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <%= link_to 'Back', posts_path, class: 'btn btn-primary mb-3'%>
    <div class="card ripple">
      <div class="card-body ripple">
        <h4 class = 'card-title text-cyprus'> Editing Posts </h4>
        <%= render 'form', post: @post, class:"text-cyprus ripple" %>
      </div>
    </div>
  </div>
  <div class= "col-md-8">
    <div>
      <%= form_with(model: [@post, @paragraph]) do |form| %>
        <%= form.hidden_field :element_type, value: 'paragraph' %>
        <%= form.submit "Paragraph", class: "mt-3 btn btn-primary mb-3" %>
      <% end %>

      <%= form_with(model: [@post, @image]) do |form| %>
        <%= form.hidden_field :element_type, value: 'image' %>
        <%= form.submit "Image", class: "btn btn-primary mb-3" %>
      <% end %>
    </div>
    <div class="card p-3 ripple text-cyprus">
      <h5> Post Preview </h5>
      <hr />
      <h2> <%= @post.title %></h2>

      <% @post.elements.each do |element| %>
          <% if element.persisted?%>
            <% if element.paragraph? %>
              <%= element.content %>
            <% elsif element.image? %>
              <% if element.image.present? %>
                <div class = "img">
                  <%= image_tag(element.image) %>
                </div>
              <% end %>
            <% end %>
          <% end %>
      <% end %>
    </div>

      <% @post.elements.each do |element| %>
        <% if element.persisted? %>
          <% if element.paragraph? %>
            <div class = "card mb-3 editCard mt-3">
              <div class = "card-body">
                  <%= form_with(model: [@post, element]) do |form| %>
                    <%= form.rich_text_area :content, class: 'mt-2 mb-2' %>
                    <%= form.submit "Save", class: " btn btn-primary btn-sm" %>
                  <% end %>
                  <%= button_to 'Delete', post_element_path(@post, element), method: :delete, class: 'mt-1 mb-2 btn btn-sm btn-danger', data: { confirm: "Are you sure?" } %>
                  </div>
              </div>
            </div>
          <% elsif element.image? %>
            <div class= "card mb-3 editCard">
              <div class= "card-body">
                  <% if element.image.present? %>
                    <div class= "img">
                      <%= image_tag(element.image)  %>
                    </div>
                    <div class="button-container text-center">
                      <%= button_to 'Delete', post_element_path(@post, element), method: :delete, class: 'mt-1 mb-2 btn btn-danger button-in-container', data: { confirm: "Are you sure?" } %>
                    </div>
                  </div>
                  <% else %>
                    <%= form_with(model: [@post, element]) do |form| %>
                      <%= form.file_field :image %>
                      <%= form.submit "Save", class: "m-3 btn btn-primary" %>
                    <% end %>
                  <%= button_to 'Delete', post_element_path(@post, element), method: :delete, class: ' btn btn-danger', data: { confirm: "Are you sure?" } %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>
<body class= 'bg-light'></body>

app/views/posts/index.html.erb
<h4 class='d-flex justify-content-between mb-4 m-4'>
  <span class="text-ripple"> Posts </span>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <%= link_to 'New Post', new_post_path, class:"btn btn-primary"%>
</h4>

<% @posts.each do |post|%>
  <div class='card mb-3 m-3 post ripple'>
    <div class='card-body post ripple'>
      <div class= "row">
        <div class= 'col-md-2'>
          <% if post.header_image.present? %>
            <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
            <div class= 'header-img' style="background-image: url(<%= url_for(post.header_image) %>);"></div>
            <% end %>
          <% end %>
        </div>

        <div class= 'col-md-9'>
          <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
            <h5 class='card-title text-dark'><%= post.title %></h5>
            <p class= 'text-secondary'><%= post.description %></p>
          <% end %>
        </div>
        <div class="col-md-1">
          <%= button_to image_tag("delete.png"), post_path(post), method: :delete, class: "btn btn-light btn-sm float-end position-top vertical-align-middle", data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<body class='bg-light'></body>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary w-100" %>
</div>

app/views/posts/show.html.erb
<h2> <%= @post.title %></h2>
<h6> Posted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.author.email %> </h6>

<% if @post.errors.any? %>
    <div class="alert alert-error">
        <% @post.errors.full_messages.join(",") %>
    </div>
<% end %>


<% @post.elements.each do |element| %>
    <% if element.element_type == "paragraph" %>
        <p> <%= element.content %> </p>
    <% elsif element.image? %>
        <% if element.image.present? %>
            <div class= "img">
              <p><%= image_tag(element.image) %></p>
            </div>
        <% end %>
    <% end %>
<% end %>

<div>
    <hr class="dashed">
    <h5><strong><%= @post.comments.count %></strong> Comments</h5>

    <div>
        <h3>Leave a reply</h3>
        <%= render 'comments/form' %>
    </div>

    <% if @post.comments.count > 0 %>
        <% @comments.each do |comment| %>
            <% if comment.persisted? %>
                <%= render 'comments/comment', post: @post, comment: comment %>
            <% end %>
        <% end %>
    <% end %>
</div>